### ISSUE TITLE
Fails to compile after the commit c8a5a65167

### ISSUE THREAD

**Issue by zenny** [mheily/rooms#20]
Rooms fails to compile after the last commit: https://github.com/mheily/rooms/commit/c8a5a65167abf9134b0b5f010965ec88a53770cd

> # ./configure
> checking for an executable docbook2man.. yes
> checking for an executable groff.. yes
> *** ERROR *** Unable to generate dependencies for Container.cc
> Please review the contents of config.log to determine the cause: 
> setting $prefix to /usr/local
> setting $libdir to /usr/local/lib
> setting $bindir to /usr/local/bin
> setting $sbindir to /usr/local/sbin
> setting $libexecdir to /usr/local/libexec
> setting $mandir to /usr/local/man
> setting $sysconfdir to /usr/local/etc
> setting $datadir to /usr/local/share
> setting $localstatedir to /var
> setting $runstatedir to /var/run
> [DEBUG] checking dependencies of Container.o:\n + c++ -std=c++14 -Wall -Werror -isystem /usr/local/include  -MM -MT Container.o Container.cc
> In file included from Container.cc:33:
> ./MountUtil.hpp:50:2: error: Not implemented yet
> #error Not implemented yet
>  ^
> ./MountUtil.hpp:86:2: error: Not implemented yet
> #error Not implemented yet
>  ^
> Container.cc:169:2: error: FIXME - port to freebsd nullfs
> #error FIXME - port to freebsd nullfs
>  ^
> 3 errors generated.
> [ERROR] Unable to generate dependencies for Container.cc

**Comment by mheily** [comment]
Yes, I'm working on a Linux port right now, which has broken the FreeBSD build. It should be fixed later this week.

**Comment by mheily** [comment]
It compiles now.
